name: K6 Performance Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  smoke-test:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run k6 smoke test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: scripts/smoke/basic.js
        env:
          ENVIRONMENT: dev
          USERNAME: ${{ secrets.TEST_USERNAME }}
          PASSWORD: ${{ secrets.TEST_PASSWORD }}

  stress-test:
    name: Run Stress Tests
    runs-on: ubuntu-latest
    needs: smoke-test  # Only run stress tests if smoke tests pass
    if: github.event_name != 'pull_request'  # Don't run stress tests on PRs
    steps:
      - uses: actions/checkout@v2

      - name: Run k6 stress test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: scripts/stress/load-test.js
        env:
          ENVIRONMENT: dev
          USERNAME: ${{ secrets.TEST_USERNAME }}
          PASSWORD: ${{ secrets.TEST_PASSWORD }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: k6-test-results
          path: outputs/ 